### ISSUE TITLE
String name signing

### ISSUE THREAD

**Issue by meesoft** [Manuel-S/FlatWindow#3]
It would be nice if the assembly was signed (just generate a .snk) so that it can be referenced by other signed assemblies.

**Comment by Fumblesneeze** [comment]
I don't really want to sign open source libraries since putting the .snk with the source would defeat it's purpose as anyone could get it and sign using it, or I would have to keep it private somewhere.

So I suggest something like this to you: https://brutaldev.com/post/NET-Assembly-Strong-Name-Signer

**Comment by meesoft** [comment]
Signing an open source library only has the purpose of making it easier to use from a signed application without having to mess with other tools.
